### ISSUE TITLE
Fonts not showing on Safari nor mobile browsers

### ISSUE THREAD

**Issue by leodrez** [rohanray/next-fonts#11]

**Comment by rohanray** [comment]
@leodrez Please can you share a minimum repro?

**Comment by leodrez** [comment]
@rohanray https://github.com/leodrez/font-error

**Comment by rohanray** [comment]
@leodrez https://github.com/rohanray/font-error. This works for me.

**Comment by leodrez** [comment]
@rohanray Does the correct font is showing on your Safari browser and Mobile Browsers? I tested on different computers and none is working. I also did a deployment to Now (https://uniqorns-website.now.sh/) and Im having the same problem.

**Comment by rohanray** [comment]
@leodrez hosted the code in https://github.com/rohanray/font-error at https://type-error-idfldxadbv.now.sh . Seems to be working fine on chrome, safari & mobile chrome.

**Comment by rohanray** [comment]
@leodrez Closing this issue since it cannot be recreated. Also, a working code has been supplied as an example
