### ISSUE TITLE
how do I use this package

### ISSUE THREAD

**Issue by dohomi** [rohanray/next-fonts#12]
Hello,
I would love to see how to use this package. I want to use it in my .scss file but no idea how to get it work.

I added the package but it does not work as soon the project is deployed via now.

I dropped my .otf|woff files inside of the /static/fonts/my-font-files. Which path do I use in my scss file?

Thanks

**Comment by rohanray** [comment]
@dohomi Please can you upload a minimal repro of your desired set-up. Thanks -RR

**Comment by dohomi** [comment]
@rohanray I am using Zeit now service. I had to add this "routes" section to make everything work. It has nothing to do with your package. 
```
    {
      "src": "^/static/fonts/(.*)$",
      "dest": "/static/fonts/$1"
    }
```

**Comment by rohanray** [comment]
Thanks @dohomi for the update! Glad that you  made it work. Regards -RR
