### ISSUE TITLE
add a new option to enable/disable content hash

### ISSUE THREAD

**Issue by nidzovito** [rohanray/next-fonts#14]
Font files are not likely to be changed, can we add `enableHash` option which is enabled by default?

https://github.com/rohanray/next-fonts/blob/362f314023c0b4bf06deb070bab5eb97aae95751/index.js#L30

**Comment by rohanray** [comment]
@nidzovito : I'm not sure I got you.

**Comment by nidzovito** [comment]
@rohanray What I wanted is add `enableHash` configuration option.

- If true, `name: '[name]-[hash].[ext]'`
- If false, `name: '[name].[ext]'`

**Comment by kachkaev** [comment]
What is a benefit of serving `'[name].[ext]'`?

**Comment by rohanray** [comment]
Closing due to no required action
