### ISSUE TITLE
AssetPrefix option not working

### ISSUE THREAD

**Issue by YagoQuinoy** [rohanray/next-fonts#22]
Hi. I'm using next-fonts local fonts example to check how it works the plugin with assetPrefix but sadly seems to not work.

Configured an ngrok that points to localhost through public url and configured assetPrefix.

![image](https://user-images.githubusercontent.com/2685554/74690537-bdacd980-51df-11ea-9d3b-fc356a46f058.png)

Seems to work for next.js assets but not for fonts

![image](https://user-images.githubusercontent.com/2685554/74690490-97873980-51df-11ea-90e4-897676c3b85f.png)

This is the next.config.js file
```
// next.config.js
const withFonts = require("next-fonts");
module.exports = withFonts({
  assetPrefix: "http://f6c62383.ngrok.io/",
  webpack(config, options) {
    return config;
  }
});
```

**Comment by YagoQuinoy** [comment]
Finally managed to make it work.

**Comment by sudheeshcm** [comment]
@YagoQuinoy How did you fix this? I'm having the same issue

**Comment by YagoQuinoy** [comment]
@sudheeshcm Let [next-sass](https://github.com/vercel/next-plugins/tree/master/packages/next-sass) plugin handle urls.

Check this commit https://github.com/rohanray/next-fonts/blob/6e4b168d39c04b7e3833721312bb3302643a69ee/index.js#L27
