### ISSUE TITLE
Flash of Invisible Text

### ISSUE THREAD

**Issue by jmayergit** [rohanray/next-fonts#25]
The [with-local-fonts](https://github.com/rohanray/next-fonts-example/tree/master/with-local-fonts) example shows a FOIT on initial page load.

Is this something that can be avoided with SSR ?

**Comment by rohanray** [comment]
This should be fixed now. Please see https://next-fonts-local-example.now.sh/ for a live demo

Please upgrade next-fonts package to 1.1.0. Thanks -RR
