### ISSUE TITLE
Not compatible with Next.js built-in CSS support

### ISSUE THREAD

**Issue by jorrit** [rohanray/next-fonts#26]
When Next.js built-in CSS is enabled the fonts are not copied to the build directory properly. Instead of their original content, they contain text like:

```js
module.exports = "/_next/static/chunks/fonts/myfont-8a32f82e77541bcdf4524e59e96b5572.woff";
```

Perhaps this commit from next-images can be applied here as well:

https://github.com/twopluszero/next-images/commit/211f6649d3af3257a83c5d16ccf4b46e096ae87c

**Comment by rohanray** [comment]
@jorrit : Thanks for reporting! Applied the same fix as mentioned by you. Please test version 1.1.0.

Regards -RR
