### ISSUE TITLE
Internal fonts not loading, example website looks broken to

### ISSUE THREAD

**Issue by yongelee** [rohanray/next-fonts#27]
I'm using Next version 9.3.4 and using next-fonts 1.0.3 and following the instructions to add local .ttf fonts to my app.

The set up is copy and pasted like the styled components example, nothing is that different.

My font files aren't being loaded, I can't find the .ttf file when I use the dev tools, I don't think next is compiling or serving font files?

I checked your example website to https://type-error-idfldxadbv.now.sh/

And this doesn't look like it's working? The dev tools say you're using Pangram font, well it doesn't look like pangram, it looks like the default serif font of the browser.

**Comment by rohanray** [comment]
@yongelee : Please see this example https://github.com/rohanray/next-fonts-styled-component-example 

Live URL : https://next-fonts-styled-component-example.now.sh/

Use version 1.1.0 of next-fonts
