### ISSUE TITLE
next.config.js

### ISSUE THREAD

**Issue by ekkis** [rohanray/next-fonts#29]
the README suggests I do:
```js
const withFonts = require('next-fonts');
module.exports = withFonts({
  webpack(config, options) {
    return config;
  }
});
```
but my `next.config.js` already contains:
```js
const withPlugins = require("next-compose-plugins")
const withImages = require("next-images")
const withSass = require("@zeit/next-sass")
const webpack = require("webpack")
const path = require("path")

module.exports = withPlugins([[withSass], [withImages]], {
  webpack(config, options) {
    config.resolve.modules.push(path.resolve("./"))
    return config
  }
})
```
sorry, but how do I integrate your module into that?

**Comment by chrishrtmn** [comment]
Not the author, but likely like this @ekkis:

const withPlugins = require("next-compose-plugins")
const withImages = require("next-images")
const withFonts = require("next-fonts")
const withSass = require("@zeit/next-sass")
const webpack = require("webpack")
const path = require("path")

module.exports = withPlugins([[withSass], [withImages], [withFonts]] {
  webpack(config, options) {
    config.resolve.modules.push(path.resolve("./"))
    return config
  }
})

**Comment by rohanray** [comment]
Thanks @chrishrtmn for helping out! @ekkis : Did it help?

**Comment by ekkis** [comment]
it did thank you

**Comment by rohanray** [comment]
@chrishrtmn : Thanks much for helping out! @ekkis : Closing the issue for now as resolved.

**Comment by rohanray** [comment]
Thanks @chrishrtmn for helping out! @ekkis : Glad to have this issue resolved and closed with help from @chrishrtmn
