### ISSUE TITLE
Is this package necessary in current Next?

### ISSUE THREAD

**Issue by mosesoak** [rohanray/next-fonts#34]
Hi @rohanray -- I've been able to successfully import and use locally-packaged fonts (in `public/fonts` directory) with `@font-face` in a `<style jsx global>` tag, in a new NextJS project, without using this package. 

Perhaps I'm confused after reading your docs description, which is simply "Import fonts in Next.js (woff, woff2, eot, ttf, otf & svg)", which again seems to work without this plugin. What functionality does this add that's not already provided?

Thank you, and thanks for your work. Just need more detail since I'm fighting bad FOUC in my stub Next app and looking for any way to get the fonts loaded and rendered in the SSG content to avoid it.

**Comment by rohanray** [comment]
@mosesoak : This plugin was created more than 2 years back. Nextjs did not have first class support for importing fonts without using plugins during those days. Hence, this plugin might not be needed for current and newer versions of Next.js

Having said that, this plugin would still be maintained for supporting projects running older versions of Next.js

**Comment by mosesoak** [comment]
@rohanray Cool, that's what I suspected, but it's not really clear from your README, timestamps (there was one recent commit showing at the top level of the repo), or the npm install trend:
![image](https://user-images.githubusercontent.com/24345/87813049-ff38c380-c815-11ea-82d6-e8bcfc0a11b9.png)

There are also a bunch of posts in the wild that recommend this extension. 

While I wouldn't want you to lose out on having a popular repo, it would be super nice of you to add to the README intro to say that this plugin is not needed in the current version of Next.

Thanks again!

**Comment by mosesoak** [comment]
Just for other people's info if they find this post, simply pointing to local fonts packaged in the public folder from `@font-face` declarations is enough. You can also add <link> tags with to preload fonts for slightly faster loading. 

However, pro tip for Google Fonts, after a bunch of testing we found that just adding a single Head link to the google font cdn, without any `@font-face` declarations, was far faster than self-hosted. So, save self-hosting for the rare cases where you actually need it!

**Comment by mosesoak** [comment]
Thanks and credit to @katesowles for figuring out that Google CDN is the fastest way to fly 🙏 🌟

**Comment by katesowles** [comment]
Forwarding thanks and credit to @wbunting and his article https://codeconqueror.com/blog/using-google-fonts-with-next-js

**Comment by deadcoder0904** [comment]
@mosesoak Am I doing it right? https://github.com/rohanray/next-fonts-example/issues/8#issue-651014594
