### ISSUE TITLE
At what version of next is this plugin deprecated?

### ISSUE THREAD

**Issue by balibebas** [rohanray/next-fonts#35]
https://github.com/rohanray/next-fonts/issues/34

Conversation was locked so I'm opening an new issue to discuss deprecation of this plugin. No one wants to see their work deprecated but it can also be a sign of good aging and useful shelf-life. Given the discussion in #34 and the note in the readme I learned this package is no longer needed. But what's not clear is at which version fo Next does is this plug-in no longer needed. Without knowing which version of NextJS this plug-in is no longer needed hundreds of individuals will be forced to do the same research to determine which is a waste of human time if it can be documented.

Personally I'm using an older version of NextJS without an upgrade path (yet) and I think I need this plug-in would be super helpful versus [hacks like this](https://github.com/vercel/next.js/issues/512#issuecomment-367164248). So does anyone know at what version of Next should this plugin be deprecated if at all?

**Comment by bryandowning** [comment]
Worth mentioning @rohanray that I needed this package for a project using an nx monorepo. There's a next.js app located in a subdirectory of the monorepo that imports a global stylesheet from outside the next.js app. Font loading choked without this plugin.

**Comment by rohanray** [comment]
@bryandowning : Thanks for sharing some valuable insights :) Really appreciate it
