### ISSUE TITLE
import from external dependency fails

### ISSUE THREAD

**Issue by jacksbox** [rohanray/next-fonts#39]
I'm using nextjs with an external dependency which loads fonts via `import FontA from '../../fonts/FontA.ttf'`
an then uses them in custom css via `styled components`...

sadly that breaks nextjs and I'm not able to get this working - using `next-fonts` I get an `SyntaxError: Invalid or unexpected token` error when trying to access a next page - any idea how to get this setup working with `next-fonts`?

**Comment by rohanray** [comment]
@jacksbox : Please see this example https://github.com/rohanray/next-fonts-example/tree/master/with-styled-comp

Also you can look at https://github.com/rohanray/next-fonts/issues/36

**Comment by rohanray** [comment]
Closing for now. @jacksbox : please create a new issue if above did not work for you
