### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by kikoanis** [rohanray/next-fonts#7]
[Line 18](https://github.com/rohanray/next-fonts/blob/master/index.js#L18) is constrained by `enableSvg` so if SVG is disabled, it won't add any loaders. I don't think that the correct intention here. I think you only need to use `enableSvg` to add svg or not to the different types of fonts

**Comment by rohanray** [comment]
Thanks @kikoanis for pointing out! That was indeed not the intention. Released v0.16.0. Can you have a  go on 0.16.0 and share your feedback? Kind regards for supporting the plugin :) Cheers!
