### ISSUE TITLE
As far as I can tell this doesn't work.

### ISSUE THREAD

**Issue by patientplatypus** [rohanray/next-fonts#8]
Can you please provide a minimal example in the repo?

**Comment by rohanray** [comment]
@patientplatypus the basic configurations are provided in Readme. Please share your configuration and if you can specify exact issue; that would help.

Also share your your package.json and next config file. Thanks!

**Comment by rohanray** [comment]
@patientplatypus Please reopen if you are still facing ay issues. Please provide above requested data too. Thanks!
